/*
 * Axesso Api
 * Use this api to fetch information to Amazon products and more.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@axesso.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * KeywordSearchResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-21T15:33:25.535Z")
public class KeywordSearchResponse {
  @SerializedName("responseStatus")
  private String responseStatus = null;

  @SerializedName("responseMessage")
  private String responseMessage = null;

  @SerializedName("sortStrategy")
  private String sortStrategy = null;

  @SerializedName("domainCode")
  private String domainCode = null;

  @SerializedName("keyword")
  private String keyword = null;

  @SerializedName("numberOfProducts")
  private Long numberOfProducts = null;

  @SerializedName("foundProducts")
  private List<String> foundProducts = null;

  public KeywordSearchResponse responseStatus(String responseStatus) {
    this.responseStatus = responseStatus;
    return this;
  }

   /**
   * Get responseStatus
   * @return responseStatus
  **/
  @ApiModelProperty(example = "PRODUCT_FOUND_RESPONSE", value = "")
  public String getResponseStatus() {
    return responseStatus;
  }

  public void setResponseStatus(String responseStatus) {
    this.responseStatus = responseStatus;
  }

  public KeywordSearchResponse responseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
    return this;
  }

   /**
   * Get responseMessage
   * @return responseMessage
  **/
  @ApiModelProperty(example = "Product successfully found!", value = "")
  public String getResponseMessage() {
    return responseMessage;
  }

  public void setResponseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
  }

  public KeywordSearchResponse sortStrategy(String sortStrategy) {
    this.sortStrategy = sortStrategy;
    return this;
  }

   /**
   * Get sortStrategy
   * @return sortStrategy
  **/
  @ApiModelProperty(example = "date-desc-rank", value = "")
  public String getSortStrategy() {
    return sortStrategy;
  }

  public void setSortStrategy(String sortStrategy) {
    this.sortStrategy = sortStrategy;
  }

  public KeywordSearchResponse domainCode(String domainCode) {
    this.domainCode = domainCode;
    return this;
  }

   /**
   * Get domainCode
   * @return domainCode
  **/
  @ApiModelProperty(example = "com", value = "")
  public String getDomainCode() {
    return domainCode;
  }

  public void setDomainCode(String domainCode) {
    this.domainCode = domainCode;
  }

  public KeywordSearchResponse keyword(String keyword) {
    this.keyword = keyword;
    return this;
  }

   /**
   * Get keyword
   * @return keyword
  **/
  @ApiModelProperty(example = "Playstation 4", value = "")
  public String getKeyword() {
    return keyword;
  }

  public void setKeyword(String keyword) {
    this.keyword = keyword;
  }

  public KeywordSearchResponse numberOfProducts(Long numberOfProducts) {
    this.numberOfProducts = numberOfProducts;
    return this;
  }

   /**
   * Get numberOfProducts
   * @return numberOfProducts
  **/
  @ApiModelProperty(value = "")
  public Long getNumberOfProducts() {
    return numberOfProducts;
  }

  public void setNumberOfProducts(Long numberOfProducts) {
    this.numberOfProducts = numberOfProducts;
  }

  public KeywordSearchResponse foundProducts(List<String> foundProducts) {
    this.foundProducts = foundProducts;
    return this;
  }

  public KeywordSearchResponse addFoundProductsItem(String foundProductsItem) {
    if (this.foundProducts == null) {
      this.foundProducts = new ArrayList<String>();
    }
    this.foundProducts.add(foundProductsItem);
    return this;
  }

   /**
   * Get foundProducts
   * @return foundProducts
  **/
  @ApiModelProperty(value = "")
  public List<String> getFoundProducts() {
    return foundProducts;
  }

  public void setFoundProducts(List<String> foundProducts) {
    this.foundProducts = foundProducts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeywordSearchResponse keywordSearchResponse = (KeywordSearchResponse) o;
    return Objects.equals(this.responseStatus, keywordSearchResponse.responseStatus) &&
        Objects.equals(this.responseMessage, keywordSearchResponse.responseMessage) &&
        Objects.equals(this.sortStrategy, keywordSearchResponse.sortStrategy) &&
        Objects.equals(this.domainCode, keywordSearchResponse.domainCode) &&
        Objects.equals(this.keyword, keywordSearchResponse.keyword) &&
        Objects.equals(this.numberOfProducts, keywordSearchResponse.numberOfProducts) &&
        Objects.equals(this.foundProducts, keywordSearchResponse.foundProducts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseStatus, responseMessage, sortStrategy, domainCode, keyword, numberOfProducts, foundProducts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeywordSearchResponse {\n");
    
    sb.append("    responseStatus: ").append(toIndentedString(responseStatus)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("    sortStrategy: ").append(toIndentedString(sortStrategy)).append("\n");
    sb.append("    domainCode: ").append(toIndentedString(domainCode)).append("\n");
    sb.append("    keyword: ").append(toIndentedString(keyword)).append("\n");
    sb.append("    numberOfProducts: ").append(toIndentedString(numberOfProducts)).append("\n");
    sb.append("    foundProducts: ").append(toIndentedString(foundProducts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

