/*
 * Axesso Api
 * Use this api to fetch information to Amazon products and more.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@axesso.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * ProductDetailsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-21T15:33:25.535Z")
public class ProductDetailsResponse {
  @SerializedName("responseStatus")
  private String responseStatus = null;

  @SerializedName("responseMessage")
  private String responseMessage = null;

  @SerializedName("productTitle")
  private String productTitle = null;

  @SerializedName("manufacturer")
  private String manufacturer = null;

  @SerializedName("countReview")
  private Long countReview = null;

  @SerializedName("answeredQuestions")
  private Long answeredQuestions = null;

  @SerializedName("productRating")
  private String productRating = null;

  @SerializedName("asin")
  private String asin = null;

  @SerializedName("sizeSelection")
  private List<String> sizeSelection = null;

  @SerializedName("soldBy")
  private String soldBy = null;

  @SerializedName("fulfilledBy")
  private String fulfilledBy = null;

  @SerializedName("warehouseAvailability")
  private String warehouseAvailability = null;

  @SerializedName("retailPrice")
  private BigDecimal retailPrice = null;

  @SerializedName("price")
  private BigDecimal price = null;

  @SerializedName("priceShippingInformation")
  private String priceShippingInformation = null;

  @SerializedName("priceSaving")
  private String priceSaving = null;

  @SerializedName("features")
  private List<String> features = null;

  @SerializedName("tags")
  private Boolean tags = null;

  public ProductDetailsResponse responseStatus(String responseStatus) {
    this.responseStatus = responseStatus;
    return this;
  }

   /**
   * Get responseStatus
   * @return responseStatus
  **/
  @ApiModelProperty(example = "PRODUCT_FOUND_RESPONSE", value = "")
  public String getResponseStatus() {
    return responseStatus;
  }

  public void setResponseStatus(String responseStatus) {
    this.responseStatus = responseStatus;
  }

  public ProductDetailsResponse responseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
    return this;
  }

   /**
   * Get responseMessage
   * @return responseMessage
  **/
  @ApiModelProperty(example = "Product successfully found!", value = "")
  public String getResponseMessage() {
    return responseMessage;
  }

  public void setResponseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
  }

  public ProductDetailsResponse productTitle(String productTitle) {
    this.productTitle = productTitle;
    return this;
  }

   /**
   * Get productTitle
   * @return productTitle
  **/
  @ApiModelProperty(example = "Playstation 4", value = "")
  public String getProductTitle() {
    return productTitle;
  }

  public void setProductTitle(String productTitle) {
    this.productTitle = productTitle;
  }

  public ProductDetailsResponse manufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

   /**
   * Get manufacturer
   * @return manufacturer
  **/
  @ApiModelProperty(example = "Sony", value = "")
  public String getManufacturer() {
    return manufacturer;
  }

  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }

  public ProductDetailsResponse countReview(Long countReview) {
    this.countReview = countReview;
    return this;
  }

   /**
   * Get countReview
   * @return countReview
  **/
  @ApiModelProperty(value = "")
  public Long getCountReview() {
    return countReview;
  }

  public void setCountReview(Long countReview) {
    this.countReview = countReview;
  }

  public ProductDetailsResponse answeredQuestions(Long answeredQuestions) {
    this.answeredQuestions = answeredQuestions;
    return this;
  }

   /**
   * Get answeredQuestions
   * @return answeredQuestions
  **/
  @ApiModelProperty(value = "")
  public Long getAnsweredQuestions() {
    return answeredQuestions;
  }

  public void setAnsweredQuestions(Long answeredQuestions) {
    this.answeredQuestions = answeredQuestions;
  }

  public ProductDetailsResponse productRating(String productRating) {
    this.productRating = productRating;
    return this;
  }

   /**
   * Get productRating
   * @return productRating
  **/
  @ApiModelProperty(example = "4.4 out of 5 stars", value = "")
  public String getProductRating() {
    return productRating;
  }

  public void setProductRating(String productRating) {
    this.productRating = productRating;
  }

  public ProductDetailsResponse asin(String asin) {
    this.asin = asin;
    return this;
  }

   /**
   * Get asin
   * @return asin
  **/
  @ApiModelProperty(example = "B077Q3YRP5", value = "")
  public String getAsin() {
    return asin;
  }

  public void setAsin(String asin) {
    this.asin = asin;
  }

  public ProductDetailsResponse sizeSelection(List<String> sizeSelection) {
    this.sizeSelection = sizeSelection;
    return this;
  }

  public ProductDetailsResponse addSizeSelectionItem(String sizeSelectionItem) {
    if (this.sizeSelection == null) {
      this.sizeSelection = new ArrayList<String>();
    }
    this.sizeSelection.add(sizeSelectionItem);
    return this;
  }

   /**
   * Get sizeSelection
   * @return sizeSelection
  **/
  @ApiModelProperty(value = "")
  public List<String> getSizeSelection() {
    return sizeSelection;
  }

  public void setSizeSelection(List<String> sizeSelection) {
    this.sizeSelection = sizeSelection;
  }

  public ProductDetailsResponse soldBy(String soldBy) {
    this.soldBy = soldBy;
    return this;
  }

   /**
   * Get soldBy
   * @return soldBy
  **/
  @ApiModelProperty(example = "Sony", value = "")
  public String getSoldBy() {
    return soldBy;
  }

  public void setSoldBy(String soldBy) {
    this.soldBy = soldBy;
  }

  public ProductDetailsResponse fulfilledBy(String fulfilledBy) {
    this.fulfilledBy = fulfilledBy;
    return this;
  }

   /**
   * Get fulfilledBy
   * @return fulfilledBy
  **/
  @ApiModelProperty(example = "Amazon", value = "")
  public String getFulfilledBy() {
    return fulfilledBy;
  }

  public void setFulfilledBy(String fulfilledBy) {
    this.fulfilledBy = fulfilledBy;
  }

  public ProductDetailsResponse warehouseAvailability(String warehouseAvailability) {
    this.warehouseAvailability = warehouseAvailability;
    return this;
  }

   /**
   * Get warehouseAvailability
   * @return warehouseAvailability
  **/
  @ApiModelProperty(example = "In Stock", value = "")
  public String getWarehouseAvailability() {
    return warehouseAvailability;
  }

  public void setWarehouseAvailability(String warehouseAvailability) {
    this.warehouseAvailability = warehouseAvailability;
  }

  public ProductDetailsResponse retailPrice(BigDecimal retailPrice) {
    this.retailPrice = retailPrice;
    return this;
  }

   /**
   * Get retailPrice
   * @return retailPrice
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getRetailPrice() {
    return retailPrice;
  }

  public void setRetailPrice(BigDecimal retailPrice) {
    this.retailPrice = retailPrice;
  }

  public ProductDetailsResponse price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public ProductDetailsResponse priceShippingInformation(String priceShippingInformation) {
    this.priceShippingInformation = priceShippingInformation;
    return this;
  }

   /**
   * Get priceShippingInformation
   * @return priceShippingInformation
  **/
  @ApiModelProperty(example = "free", value = "")
  public String getPriceShippingInformation() {
    return priceShippingInformation;
  }

  public void setPriceShippingInformation(String priceShippingInformation) {
    this.priceShippingInformation = priceShippingInformation;
  }

  public ProductDetailsResponse priceSaving(String priceSaving) {
    this.priceSaving = priceSaving;
    return this;
  }

   /**
   * Get priceSaving
   * @return priceSaving
  **/
  @ApiModelProperty(example = "You Save: $59,58 (43%)", value = "")
  public String getPriceSaving() {
    return priceSaving;
  }

  public void setPriceSaving(String priceSaving) {
    this.priceSaving = priceSaving;
  }

  public ProductDetailsResponse features(List<String> features) {
    this.features = features;
    return this;
  }

  public ProductDetailsResponse addFeaturesItem(String featuresItem) {
    if (this.features == null) {
      this.features = new ArrayList<String>();
    }
    this.features.add(featuresItem);
    return this;
  }

   /**
   * Get features
   * @return features
  **/
  @ApiModelProperty(value = "")
  public List<String> getFeatures() {
    return features;
  }

  public void setFeatures(List<String> features) {
    this.features = features;
  }

  public ProductDetailsResponse tags(Boolean tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public Boolean isTags() {
    return tags;
  }

  public void setTags(Boolean tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductDetailsResponse productDetailsResponse = (ProductDetailsResponse) o;
    return Objects.equals(this.responseStatus, productDetailsResponse.responseStatus) &&
        Objects.equals(this.responseMessage, productDetailsResponse.responseMessage) &&
        Objects.equals(this.productTitle, productDetailsResponse.productTitle) &&
        Objects.equals(this.manufacturer, productDetailsResponse.manufacturer) &&
        Objects.equals(this.countReview, productDetailsResponse.countReview) &&
        Objects.equals(this.answeredQuestions, productDetailsResponse.answeredQuestions) &&
        Objects.equals(this.productRating, productDetailsResponse.productRating) &&
        Objects.equals(this.asin, productDetailsResponse.asin) &&
        Objects.equals(this.sizeSelection, productDetailsResponse.sizeSelection) &&
        Objects.equals(this.soldBy, productDetailsResponse.soldBy) &&
        Objects.equals(this.fulfilledBy, productDetailsResponse.fulfilledBy) &&
        Objects.equals(this.warehouseAvailability, productDetailsResponse.warehouseAvailability) &&
        Objects.equals(this.retailPrice, productDetailsResponse.retailPrice) &&
        Objects.equals(this.price, productDetailsResponse.price) &&
        Objects.equals(this.priceShippingInformation, productDetailsResponse.priceShippingInformation) &&
        Objects.equals(this.priceSaving, productDetailsResponse.priceSaving) &&
        Objects.equals(this.features, productDetailsResponse.features) &&
        Objects.equals(this.tags, productDetailsResponse.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseStatus, responseMessage, productTitle, manufacturer, countReview, answeredQuestions, productRating, asin, sizeSelection, soldBy, fulfilledBy, warehouseAvailability, retailPrice, price, priceShippingInformation, priceSaving, features, tags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductDetailsResponse {\n");
    
    sb.append("    responseStatus: ").append(toIndentedString(responseStatus)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("    productTitle: ").append(toIndentedString(productTitle)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    countReview: ").append(toIndentedString(countReview)).append("\n");
    sb.append("    answeredQuestions: ").append(toIndentedString(answeredQuestions)).append("\n");
    sb.append("    productRating: ").append(toIndentedString(productRating)).append("\n");
    sb.append("    asin: ").append(toIndentedString(asin)).append("\n");
    sb.append("    sizeSelection: ").append(toIndentedString(sizeSelection)).append("\n");
    sb.append("    soldBy: ").append(toIndentedString(soldBy)).append("\n");
    sb.append("    fulfilledBy: ").append(toIndentedString(fulfilledBy)).append("\n");
    sb.append("    warehouseAvailability: ").append(toIndentedString(warehouseAvailability)).append("\n");
    sb.append("    retailPrice: ").append(toIndentedString(retailPrice)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceShippingInformation: ").append(toIndentedString(priceShippingInformation)).append("\n");
    sb.append("    priceSaving: ").append(toIndentedString(priceSaving)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

