/*
 * Axesso Api
 * Use this api to fetch information to Amazon products and more.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@axesso.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SortOptionResponseSortOptions;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SortOptionResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-21T15:33:25.535Z")
public class SortOptionResponse {
  @SerializedName("responseStatus")
  private String responseStatus = null;

  @SerializedName("responseMessage")
  private String responseMessage = null;

  @SerializedName("resultSize")
  private Long resultSize = null;

  @SerializedName("sortOptions")
  private List<SortOptionResponseSortOptions> sortOptions = null;

  public SortOptionResponse responseStatus(String responseStatus) {
    this.responseStatus = responseStatus;
    return this;
  }

   /**
   * Get responseStatus
   * @return responseStatus
  **/
  @ApiModelProperty(example = "PRODUCT_FOUND_RESPONSE", value = "")
  public String getResponseStatus() {
    return responseStatus;
  }

  public void setResponseStatus(String responseStatus) {
    this.responseStatus = responseStatus;
  }

  public SortOptionResponse responseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
    return this;
  }

   /**
   * Get responseMessage
   * @return responseMessage
  **/
  @ApiModelProperty(example = "Product successfully found!", value = "")
  public String getResponseMessage() {
    return responseMessage;
  }

  public void setResponseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
  }

  public SortOptionResponse resultSize(Long resultSize) {
    this.resultSize = resultSize;
    return this;
  }

   /**
   * Get resultSize
   * @return resultSize
  **/
  @ApiModelProperty(value = "")
  public Long getResultSize() {
    return resultSize;
  }

  public void setResultSize(Long resultSize) {
    this.resultSize = resultSize;
  }

  public SortOptionResponse sortOptions(List<SortOptionResponseSortOptions> sortOptions) {
    this.sortOptions = sortOptions;
    return this;
  }

  public SortOptionResponse addSortOptionsItem(SortOptionResponseSortOptions sortOptionsItem) {
    if (this.sortOptions == null) {
      this.sortOptions = new ArrayList<SortOptionResponseSortOptions>();
    }
    this.sortOptions.add(sortOptionsItem);
    return this;
  }

   /**
   * Get sortOptions
   * @return sortOptions
  **/
  @ApiModelProperty(value = "")
  public List<SortOptionResponseSortOptions> getSortOptions() {
    return sortOptions;
  }

  public void setSortOptions(List<SortOptionResponseSortOptions> sortOptions) {
    this.sortOptions = sortOptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SortOptionResponse sortOptionResponse = (SortOptionResponse) o;
    return Objects.equals(this.responseStatus, sortOptionResponse.responseStatus) &&
        Objects.equals(this.responseMessage, sortOptionResponse.responseMessage) &&
        Objects.equals(this.resultSize, sortOptionResponse.resultSize) &&
        Objects.equals(this.sortOptions, sortOptionResponse.sortOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseStatus, responseMessage, resultSize, sortOptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SortOptionResponse {\n");
    
    sb.append("    responseStatus: ").append(toIndentedString(responseStatus)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("    resultSize: ").append(toIndentedString(resultSize)).append("\n");
    sb.append("    sortOptions: ").append(toIndentedString(sortOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

