/*
 * Axesso Api
 * Use this api to fetch information to Amazon products and more.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@axesso.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BuyRecommendationResponse;
import io.swagger.client.model.KeywordSearchResponse;
import io.swagger.client.model.ProductDetailsResponse;
import io.swagger.client.model.SortOptionResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AmzApi
 */
@Ignore
public class AmzApiTest {

    private final AmzApi api = new AmzApi();

    
    /**
     * fetch results auf a keyword search on Amazon
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void keywordSearchTest() throws ApiException {
        String keyword = null;
        String domainCode = null;
        String sortBy = null;
        Integer numberOfProducts = null;
        KeywordSearchResponse response = api.keywordSearch(keyword, domainCode, sortBy, numberOfProducts);

        // TODO: test validations
    }
    
    /**
     * request buy recommendations to a given product
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestBuyRecommendationTest() throws ApiException {
        String url = null;
        BuyRecommendationResponse response = api.requestBuyRecommendation(url);

        // TODO: test validations
    }
    
    /**
     * lookup product information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestProductTest() throws ApiException {
        String url = null;
        String size = null;
        ProductDetailsResponse response = api.requestProduct(url, size);

        // TODO: test validations
    }
    
    /**
     * request available sort options to use in keyword search
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sortOptionsTest() throws ApiException {
        SortOptionResponse response = api.sortOptions();

        // TODO: test validations
    }
    
}
